# Generated by Django 3.2.16 on 2023-02-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_author_comment_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='owner',
            new_name='author',
        ),
    ]
